# Generated by Django 5.2.10 on 2026-02-25 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255, verbose_name='Shaxs F.I.Sh')),
                ('fish_inisiali', models.CharField(blank=True, max_length=100, verbose_name='F.I.Sh (Inisiali)')),
                ('pasport_seriya', models.CharField(blank=True, max_length=20, verbose_name='Pasport seriyasi va raqami')),
                ('pasport_berilgan', models.CharField(blank=True, max_length=255, verbose_name='Kim tomonidan berilgan')),
                ('jshshir', models.BigIntegerField(blank=True, null=True, verbose_name='JSHSHIR')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('jinsi', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.TextField(blank=True, verbose_name='Yashash manzili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mijoz/Shaxs',
                'verbose_name_plural': 'Mijozlar/Shaxslar',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shablon nomi')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Word fayl (.docx)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod (unikal)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('avto', 'Avtomobil'), ('kochmas', "Ko'chmas mulk"), ('tilla', 'Tilla buyumlar'), ('sugurta', "Sug'urta polisi")], max_length=20, verbose_name='Garov Turi')),
                ('owner_type', models.CharField(choices=[('borrower', "O'zi (Qarz oluvchi)"), ('other', 'Uchinchi shaxs'), ('general_proxy', 'Bosh ishonchnoma (Notarius)')], default='borrower', max_length=20, verbose_name='Garov egasi turi')),
                ('notarius_fish', models.CharField(blank=True, max_length=255, verbose_name='Notarius F.I.Sh')),
                ('notarius_address', models.CharField(blank=True, max_length=255, verbose_name='Notarius manzili')),
                ('reestr_number', models.CharField(blank=True, max_length=100, verbose_name='Reestr raqami')),
                ('reestr_date', models.DateField(blank=True, null=True, verbose_name='Reestr sanasi')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_collaterals', to='document_processor.client')),
            ],
        ),
        migrations.CreateModel(
            name='AutoCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100, verbose_name='Modeli')),
                ('kuzov_turi', models.CharField(blank=True, max_length=50, verbose_name='Kuzov turi')),
                ('kuzov_raqami', models.CharField(blank=True, max_length=50, verbose_name='Kuzov raqami')),
                ('dvigatel', models.CharField(blank=True, max_length=50, verbose_name='Dvigatel')),
                ('shassi', models.CharField(blank=True, default='RAKAMSIZ', max_length=50, verbose_name='Shassi')),
                ('rang', models.CharField(blank=True, max_length=50, verbose_name='Rangi')),
                ('yil', models.IntegerField(blank=True, null=True, verbose_name='Ishlab chiqarilgan yili')),
                ('texpasport', models.CharField(blank=True, max_length=50, verbose_name='Texpasport')),
                ('texpasport_sana', models.DateField(blank=True, null=True, verbose_name='Texpasport sanasi')),
                ('manzil', models.CharField(blank=True, max_length=255, verbose_name="Ro'yxatdan o'tgan manzil")),
                ('davlat_raqami', models.CharField(blank=True, max_length=20, verbose_name='Davlat raqami')),
                ('bahosi', models.BigIntegerField(blank=True, null=True, verbose_name='Baholangan qiymati')),
                ('bahosi_soz', models.CharField(blank=True, max_length=255, verbose_name="Qiymat so'z bilan")),
                ('collateral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_detail', to='document_processor.collateral')),
            ],
        ),
        migrations.CreateModel(
            name='GoldCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(blank=True, verbose_name='Buyumlar nomi/tavsifi')),
                ('probi', models.CharField(blank=True, max_length=20, verbose_name='Probsi')),
                ('vazni', models.CharField(blank=True, max_length=50, verbose_name='Vazni (gr)')),
                ('soni', models.IntegerField(blank=True, null=True, verbose_name='Soni (dona)')),
                ('bahosi', models.BigIntegerField(blank=True, null=True, verbose_name='Baholangan qiymati')),
                ('bahosi_soz', models.CharField(blank=True, max_length=255, verbose_name="Garov qiymati so'z bilan")),
                ('collateral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_detail', to='document_processor.collateral')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya', models.CharField(blank=True, max_length=255, verbose_name="Sug'urta kompaniyasi")),
                ('polis_raqami', models.CharField(blank=True, max_length=50, verbose_name='Polis raqami')),
                ('sana', models.DateField(blank=True, null=True, verbose_name="Sug'urta sanasi")),
                ('summa', models.BigIntegerField(blank=True, null=True, verbose_name="Sug'urta summasi")),
                ('summa_soz', models.CharField(blank=True, max_length=255, verbose_name="Sug'urta summasi so'z bilan")),
                ('collateral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_detail', to='document_processor.collateral')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_moderator', 'Moderator Tasdiqi Kutilmoqda'), ('pending_director', 'Direktor Tasdiqi Kutilmoqda'), ('completed', 'Tasdiqlandi (Yakunlandi)'), ('rejected', 'Rad Etildi')], default='pending_moderator', max_length=20, verbose_name='Holati')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('moderator_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderator tasdiqlagan vaqt')),
                ('director_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan vaqt')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='loan_docs/', verbose_name='Ziplangan Hujjatlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='document_processor.client', verbose_name='Qarz Oluvchi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_loans', to=settings.AUTH_USER_MODEL, verbose_name='Direktor')),
                ('moderator_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_loans', to=settings.AUTH_USER_MODEL, verbose_name='Moderator')),
            ],
            options={
                'verbose_name': 'Kredit Arizasi',
                'verbose_name_plural': 'Kredit Arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_joyi', models.TextField(blank=True, verbose_name='Ish joyi va lavozimi')),
                ('daromad', models.BigIntegerField(blank=True, null=True, verbose_name='Oylik daromad')),
                ('xarajatlar', models.BigIntegerField(blank=True, null=True, verbose_name='Oylik xarajatlar')),
                ('tahminiy_tolov', models.BigIntegerField(blank=True, null=True, verbose_name="Tahminiy oylik to'lov")),
                ('majburiyatlar', models.TextField(blank=True, verbose_name='Miyjud qarz majburiyatlari')),
                ('filial_nomi', models.CharField(choices=[('Buxoro filiali', 'Buxoro filiali'), ('Samarqand filiali', 'Samarqand filiali'), ('Toshkent shahar filiali', 'Toshkent shahar filiali'), ('Andijon filiali', 'Andijon filiali'), ("Farg'ona filiali", "Farg'ona filiali"), ('Namangan filiali', 'Namangan filiali'), ('Qashqadaryo filiali', 'Qashqadaryo filiali'), ('Surxondaryo filiali', 'Surxondaryo filiali'), ('Jizzax filiali', 'Jizzax filiali'), ('Navoiy filiali', 'Navoiy filiali'), ('Xorazm filiali', 'Xorazm filiali'), ("To'rtko'l filiali", "To'rtko'l filiali")], default='Buxoro filiali', max_length=100, verbose_name='Filial nomi')),
                ('filial_boshligi', models.CharField(blank=True, max_length=255, verbose_name="Filial boshlig'i F.I.Sh")),
                ('filial_boshligi_inisiali', models.CharField(blank=True, max_length=100, verbose_name="Filial boshlig'i Inisiali")),
                ('tashkilot_nomi', models.CharField(default='«PULLOL BUSINESS MIKROMOLIYA TASHKILOTI» MChJ', max_length=255, verbose_name='Tashkilot nomi')),
                ('direktor_fish', models.CharField(blank=True, default="OBIDOV ABDULLA SHOKIR O'G'LI", max_length=255, verbose_name='Direktor F.I.Sh')),
                ('direktor_fish_inisiali', models.CharField(blank=True, default='A.SH.OBIDOV', max_length=100, verbose_name='Direktor Inisiali')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='document_processor.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(blank=True, max_length=255, verbose_name='F.I.Sh')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('qarindoshlik', models.CharField(blank=True, choices=[('turmush_ortogi', "Turmush o'rtog'i"), ('ota', 'Ota'), ('ona', 'Ona'), ('aka', 'Aka'), ('uka', 'Uka'), ('opa', 'Opa'), ('singil', 'Singil')], max_length=50, verbose_name='Qarindoshligi')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='document_processor.loanapplication')),
            ],
        ),
        migrations.AddField(
            model_name='collateral',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='document_processor.loanapplication'),
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.CharField(blank=True, max_length=50, verbose_name='Kredit shartnomasi raqami')),
                ('shartnoma_sanasi', models.DateField(blank=True, null=True, verbose_name='Shartnoma sanasi')),
                ('miqdori', models.BigIntegerField(blank=True, null=True, verbose_name='Kredit miqdori (raqam bilan)')),
                ('miqdori_soz', models.CharField(blank=True, max_length=255, verbose_name="Kredit miqdori (so'z bilan)")),
                ('muddat_oy', models.CharField(blank=True, max_length=10, verbose_name='Kredit muddati (oy)')),
                ('muddat_oy_soz', models.CharField(blank=True, max_length=255, verbose_name="Kredit muddati (so'z bilan)")),
                ('foiz', models.CharField(blank=True, max_length=10, verbose_name='Foiz stavkasi (raqam)')),
                ('foiz_soz', models.CharField(blank=True, max_length=255, verbose_name="Foiz stavkasi (so'z bilan)")),
                ('turi', models.CharField(choices=[('mikroqarz', 'Mikroqarz'), ('mikrokredit', 'Mikrokredit')], default='mikroqarz', max_length=20, verbose_name='Kredit turi')),
                ('grafik_turi', models.CharField(choices=[('annuitet', 'Annuitet'), ('differensial', 'Differensial')], default='differensial', max_length=20, verbose_name="To'lov grafigi")),
                ('grafik_matni', models.TextField(blank=True, verbose_name='Grafik jadvali (Exceldan)')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='document_processor.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(blank=True, max_length=100, verbose_name='Mulk turi (Uy/Kvartira)')),
                ('umumiy_maydon', models.CharField(blank=True, max_length=50, verbose_name='Umumiy maydon')),
                ('qurilish_maydon', models.CharField(blank=True, max_length=50, verbose_name='Qurilish maydoni')),
                ('foydalanish_maydon', models.CharField(blank=True, max_length=50, verbose_name='Foydalanish maydoni')),
                ('yashash_maydon', models.CharField(blank=True, max_length=50, verbose_name='Yashash maydoni')),
                ('reestr_raqami', models.CharField(blank=True, max_length=50, verbose_name='Mulk reestr raqami')),
                ('kadastr_raqami', models.CharField(blank=True, max_length=100, verbose_name='Kadastr raqami')),
                ('manzil', models.TextField(blank=True, verbose_name='Mulk manzili')),
                ('bahosi', models.BigIntegerField(blank=True, null=True, verbose_name='Garov qiymati')),
                ('bahosi_soz', models.CharField(blank=True, max_length=255, verbose_name="Garov qiymati so'z bilan")),
                ('collateral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='document_processor.collateral')),
            ],
        ),
    ]
