# Generated by Django 5.2.10 on 2026-02-26 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocollateral',
            name='bahosi_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qiymat so'z bilan"),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='collateral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_detail', to='document_processor.collateral'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='davlat_raqami',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Davlat raqami'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='dvigatel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dvigatel'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='kuzov_raqami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kuzov raqami'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='kuzov_turi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kuzov turi'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='manzil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ro'yxatdan o'tgan manzil"),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='nomi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modeli'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='rang',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='shassi',
            field=models.CharField(blank=True, default='RAKAMSIZ', max_length=50, null=True, verbose_name='Shassi'),
        ),
        migrations.AlterField(
            model_name='autocollateral',
            name='texpasport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texpasport'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shaxs F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fish_inisiali',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh (Inisiali)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pasport_berilgan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kim tomonidan berilgan'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pasport_seriya',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasport seriyasi va raqami'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='document_processor.loanapplication'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='notarius_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notarius manzili'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='notarius_fish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notarius F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('borrower', "O'zi (Qarz oluvchi)"), ('other', 'Uchinchi shaxs'), ('general_proxy', 'Bosh ishonchnoma (Notarius)')], default='borrower', max_length=20, null=True, verbose_name='Garov egasi turi'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='reestr_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reestr raqami'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='type',
            field=models.CharField(blank=True, choices=[('avto', 'Avtomobil'), ('kochmas', "Ko'chmas mulk"), ('tilla', 'Tilla buyumlar'), ('sugurta', "Sug'urta polisi")], max_length=20, null=True, verbose_name='Garov Turi'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='document_processor.loanapplication'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='fish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='qarindoshlik',
            field=models.CharField(blank=True, choices=[('turmush_ortogi', "Turmush o'rtog'i"), ('ota', 'Ota'), ('ona', 'Ona'), ('aka', 'Aka'), ('uka', 'Uka'), ('opa', 'Opa'), ('singil', 'Singil')], max_length=50, null=True, verbose_name='Qarindoshligi'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Kod (unikal)'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='Word fayl (.docx)'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shablon nomi'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='document_processor.loanapplication'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='direktor_fish',
            field=models.CharField(blank=True, default="OBIDOV ABDULLA SHOKIR O'G'LI", max_length=255, null=True, verbose_name='Direktor F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='direktor_fish_inisiali',
            field=models.CharField(blank=True, default='A.SH.OBIDOV', max_length=100, null=True, verbose_name='Direktor Inisiali'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='filial_boshligi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Filial boshlig'i F.I.Sh"),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='filial_boshligi_inisiali',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Filial boshlig'i Inisiali"),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='filial_nomi',
            field=models.CharField(blank=True, choices=[('Buxoro filiali', 'Buxoro filiali'), ('Samarqand filiali', 'Samarqand filiali'), ('Toshkent shahar filiali', 'Toshkent shahar filiali'), ('Andijon filiali', 'Andijon filiali'), ("Farg'ona filiali", "Farg'ona filiali"), ('Namangan filiali', 'Namangan filiali'), ('Qashqadaryo filiali', 'Qashqadaryo filiali'), ('Surxondaryo filiali', 'Surxondaryo filiali'), ('Jizzax filiali', 'Jizzax filiali'), ('Navoiy filiali', 'Navoiy filiali'), ('Xorazm filiali', 'Xorazm filiali'), ("To'rtko'l filiali", "To'rtko'l filiali")], default='Buxoro filiali', max_length=100, null=True, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='ish_joyi',
            field=models.TextField(blank=True, null=True, verbose_name='Ish joyi va lavozimi'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='majburiyatlar',
            field=models.TextField(blank=True, null=True, verbose_name='Miyjud qarz majburiyatlari'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='tashkilot_nomi',
            field=models.CharField(blank=True, default='«PULLOL BUSINESS MIKROMOLIYA TASHKILOTI» MChJ', max_length=255, null=True, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='goldcollateral',
            name='bahosi_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Garov qiymati so'z bilan"),
        ),
        migrations.AlterField(
            model_name='goldcollateral',
            name='collateral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_detail', to='document_processor.collateral'),
        ),
        migrations.AlterField(
            model_name='goldcollateral',
            name='nomi',
            field=models.TextField(blank=True, null=True, verbose_name='Buyumlar nomi/tavsifi'),
        ),
        migrations.AlterField(
            model_name='goldcollateral',
            name='probi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Probsi'),
        ),
        migrations.AlterField(
            model_name='goldcollateral',
            name='vazni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vazni (gr)'),
        ),
        migrations.AlterField(
            model_name='insurancecollateral',
            name='collateral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_detail', to='document_processor.collateral'),
        ),
        migrations.AlterField(
            model_name='insurancecollateral',
            name='kompaniya',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Sug'urta kompaniyasi"),
        ),
        migrations.AlterField(
            model_name='insurancecollateral',
            name='polis_raqami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Polis raqami'),
        ),
        migrations.AlterField(
            model_name='insurancecollateral',
            name='summa_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Sug'urta summasi so'z bilan"),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='document_processor.client', verbose_name='Qarz Oluvchi'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('pending_moderator', 'Moderator Tasdiqi Kutilmoqda'), ('pending_director', 'Direktor Tasdiqi Kutilmoqda'), ('completed', 'Tasdiqlandi (Yakunlandi)'), ('rejected', 'Rad Etildi')], default='pending_moderator', max_length=20, null=True, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='document_processor.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='foiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Foiz stavkasi (raqam)'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='foiz_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Foiz stavkasi (so'z bilan)"),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='grafik_matni',
            field=models.TextField(blank=True, null=True, verbose_name='Grafik jadvali (Exceldan)'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='grafik_turi',
            field=models.CharField(blank=True, choices=[('annuitet', 'Annuitet'), ('differensial', 'Differensial')], default='differensial', max_length=20, null=True, verbose_name="To'lov grafigi"),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='miqdori_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Kredit miqdori (so'z bilan)"),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='muddat_oy',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kredit muddati (oy)'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='muddat_oy_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Kredit muddati (so'z bilan)"),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='shartnoma_raqami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kredit shartnomasi raqami'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='turi',
            field=models.CharField(blank=True, choices=[('mikroqarz', 'Mikroqarz'), ('mikrokredit', 'Mikrokredit')], default='mikroqarz', max_length=20, null=True, verbose_name='Kredit turi'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='bahosi_soz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Garov qiymati so'z bilan"),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='collateral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='document_processor.collateral'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='foydalanish_maydon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Foydalanish maydoni'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='kadastr_raqami',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kadastr raqami'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Mulk manzili'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='qurilish_maydon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qurilish maydoni'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='reestr_raqami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mulk reestr raqami'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='turi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mulk turi (Uy/Kvartira)'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='umumiy_maydon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Umumiy maydon'),
        ),
        migrations.AlterField(
            model_name='realestatecollateral',
            name='yashash_maydon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yashash maydoni'),
        ),
    ]
