# Generated by Django 5.2.10 on 2026-01-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='director_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='moderator_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='moderator_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='status',
            field=models.CharField(choices=[('pending_moderator', 'Moderator Kutilmoqda'), ('pending_director', 'Direktor Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad Etildi')], default='pending_moderator', max_length=20),
        ),
    ]
