# Generated by Django 5.2.10 on 2026-01-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0002_processeddocument_director_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='generation_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
