# Generated by Django 5.2.11 on 2026-02-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0002_alter_autocollateral_bahosi_soz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='pdf_file',
        ),
    ]
