# Generated by Django 5.2.11 on 2026-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0003_remove_loanapplication_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name="Asl JSON ma'lumotlari"),
        ),
    ]
