# Generated by Django 5.2.10 on 2026-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0003_processeddocument_generation_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='borrower_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qarz oluvchi FIO'),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='collateral_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Garov nomi'),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='credit_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kredit summasi'),
        ),
    ]
