# Generated by Django 5.2.11 on 2026-02-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0004_loanapplication_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ish_joyi',
            field=models.TextField(blank=True, null=True, verbose_name='Ish joyi'),
        ),
    ]
