# Generated by Django 5.2.11 on 2026-02-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0005_client_ish_joyi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ish_joyi',
        ),
    ]
