# Generated by Django 5.2.10 on 2026-02-01 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0005_documenttemplate_loanagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi (Operator)'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan vaqt'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='director_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_loans', to=settings.AUTH_USER_MODEL, verbose_name='Direktor'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='moderator_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Moderator tasdiqlagan vaqt'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='moderator_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_loans', to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/', verbose_name="Hujjatlar To'plami (ZIP)"),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='status',
            field=models.CharField(choices=[('pending_moderator', 'Moderator Tasdiqi Kutilmoqda'), ('pending_director', 'Direktor Tasdiqi Kutilmoqda'), ('completed', 'Tasdiqlandi (Yakunlandi)'), ('rejected', 'Rad Etildi')], default='pending_moderator', max_length=20, verbose_name='Holati'),
        ),
    ]
