# Generated by Django 5.2.10 on 2026-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0006_loanagreement_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='avto_kuzov_turi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kuzov turi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='avto_shassi',
            field=models.CharField(blank=True, default='RAKAMSIZ', max_length=50, verbose_name='Shassi raqami'),
        ),
    ]
