# Generated by Django 5.2.11 on 2026-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0006_remove_client_ish_joyi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='boshlanish_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='tugash_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
    ]
