# Generated by Django 5.2.10 on 2026-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0007_loanagreement_avto_kuzov_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='avto_manzil',
            field=models.CharField(blank=True, max_length=255, verbose_name="Avto ro'yxatdan o'tgan manzili"),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='avto_texpasport',
            field=models.CharField(blank=True, max_length=50, verbose_name='Texpasport'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='avto_yurgan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yurgan masofasi'),
        ),
    ]
