# Generated by Django 5.2.11 on 2026-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0007_loandetails_boshlanish_sanasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinfo',
            name='aloqa_ish_tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ish telefoni raqami'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='aloqa_uy_tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uy telefoni raqami'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='aloqa_uyali_tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uyali telefon raqami'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='daromad_asosiy',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ish haqi (asosiy ish)'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='daromad_boshqa',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Boshqa daromadlar'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='daromad_orindosh',
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Ish haqi (o'rindoshlik)"),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='ish_lavozim',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='ish_manzil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ro'yxatdan o'tish manzili"),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='ish_muassasa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Muassasa nomlanishi'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='xarajat_boshqa',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Boshqa xarajatlar'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='xarajat_kommunal',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Uy-joy va kommunal'),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='xarajat_oilaviy',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Oilaviy xarajatlar'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='daromad',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Jami daromad'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='xarajatlar',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Jami xarajatlar'),
        ),
    ]
