# Generated by Django 5.2.10 on 2026-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0008_loanagreement_avto_manzil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='avto_bahosi_soz',
            field=models.CharField(blank=True, max_length=255, verbose_name="Baholangan qiymati (so'z bilan)"),
        ),
    ]
