# Generated by Django 5.2.10 on 2026-03-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0009_auto_20260315_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinfo',
            name='ish_joyi',
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='tahminiy_tolov',
        ),
    ]
