# Generated by Django 5.2.10 on 2026-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0009_loanagreement_avto_bahosi_soz'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_daromad',
            field=models.CharField(blank=True, max_length=50, verbose_name="O'rtacha oylik daromad"),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_ish_joyi',
            field=models.TextField(blank=True, verbose_name='Ish joyi va lavozimi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_majburiyatlar',
            field=models.TextField(blank=True, verbose_name='Mavjud kredit va qarz majburiyatlari'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_xarajatlar',
            field=models.CharField(blank=True, max_length=50, verbose_name="O'rtacha oylik xarajatlar"),
        ),
    ]
