# Generated by Django 5.2.10 on 2026-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0010_loanagreement_qarz_oluvchi_daromad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_tahminiy_tolov',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mikroqarz bo‘yicha oylik differensial to‘lovi miqdori (tahminiy)'),
        ),
    ]
