# Generated by Django 5.2.12 on 2026-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0010_remove_financialinfo_ish_joyi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanWizardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name="Barcha to'plangan ma'lumotlar (JSON)")),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz F.I.Sh')),
                ('loan_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Kredit summasi')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wizard Arizasi',
                'verbose_name_plural': 'Wizard Arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='filial_nomi',
            field=models.CharField(blank=True, choices=[('Buxoro filiali', 'Buxoro filiali'), ("To'rtko'l filiali", "To'rtko'l filiali"), ('Urganch filiali', 'Urganch filiali'), ('Samarqand filiali', 'Samarqand filiali'), ('Toshkent shahar filiali', 'Toshkent shahar filiali'), ('Andijon filiali', 'Andijon filiali'), ("Farg'ona filiali", "Farg'ona filiali"), ('Namangan filiali', 'Namangan filiali'), ('Qashqadaryo filiali', 'Qashqadaryo filiali'), ('Surxondaryo filiali', 'Surxondaryo filiali'), ('Jizzax filiali', 'Jizzax filiali'), ('Navoiy filiali', 'Navoiy filiali'), ('Xorazm filiali', 'Xorazm filiali')], default='Buxoro filiali', max_length=100, null=True, verbose_name='Filial nomi'),
        ),
    ]
