# Generated by Django 5.2.12 on 2026-03-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0011_loanwizardapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='wizard_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_loans', to='document_processor.loanwizardapplication'),
        ),
    ]
