# Generated by Django 5.2.10 on 2026-02-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0011_loanagreement_qarz_oluvchi_tahminiy_tolov'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='avto_texpasport_sana',
            field=models.CharField(blank=True, max_length=20, verbose_name='Texpasport berilgan sanasi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='grafik',
            field=models.CharField(choices=[('annuitet', 'Annuitet'), ('differensial', 'Differensial')], default='differensial', max_length=20, verbose_name="To'lov grafigi"),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_1_fish',
            field=models.CharField(blank=True, max_length=255, verbose_name='1-kontakt F.I.Sh'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_1_qarindoshlik',
            field=models.CharField(blank=True, max_length=50, verbose_name='1-kontakt Qarindoshligi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_1_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='1-kontakt Telefoni'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_2_fish',
            field=models.CharField(blank=True, max_length=255, verbose_name='2-kontakt F.I.Sh'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_2_qarindoshlik',
            field=models.CharField(blank=True, max_length=50, verbose_name='2-kontakt Qarindoshligi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_2_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='2-kontakt Telefoni'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_3_fish',
            field=models.CharField(blank=True, max_length=255, verbose_name='3-kontakt F.I.Sh'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_3_qarindoshlik',
            field=models.CharField(blank=True, max_length=50, verbose_name='3-kontakt Qarindoshligi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kontakt_3_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='3-kontakt Telefoni'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='kredit_turi',
            field=models.CharField(choices=[('mikroqarz', 'Mikroqarz'), ('mikrokredit', 'Mikrokredit')], default='mikroqarz', max_length=20, verbose_name='Kredit turi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
    ]
