# Generated by Django 5.2.10 on 2026-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0012_loanagreement_avto_texpasport_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanagreement',
            name='avto_texpasport_sana',
            field=models.DateField(blank=True, null=True, verbose_name='Texpasport berilgan sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='ishonchnoma_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Ishonchnoma sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='monitoring_sana_1',
            field=models.DateField(blank=True, null=True, verbose_name='1-monitoring sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='monitoring_sana_2',
            field=models.DateField(blank=True, null=True, verbose_name='2-monitoring sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='monitoring_sana_3',
            field=models.DateField(blank=True, null=True, verbose_name='3-monitoring sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='monitoring_sana_4',
            field=models.DateField(blank=True, null=True, verbose_name='4-monitoring sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='mulk_dalolatnoma_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Baholash dalolatnoma sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='qarz_oluvchi_tugilgan_sana',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='shartnoma_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Shartnoma sanasi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='sugurta_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name="Sug'urta sanasi"),
        ),
    ]
