# Generated by Django 5.2.12 on 2026-03-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0012_loanapplication_wizard_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocollateral',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='collateral',
            name='owner_client',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='client',
        ),
        migrations.RemoveField(
            model_name='collateral',
            name='application',
        ),
        migrations.RemoveField(
            model_name='insurancecollateral',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='realestatecollateral',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='goldcollateral',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='application',
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='application',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='director_approved_by',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='moderator_approved_by',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='wizard_app',
        ),
        migrations.RemoveField(
            model_name='loandetails',
            name='application',
        ),
        migrations.DeleteModel(
            name='ProcessedDocument',
        ),
        migrations.DeleteModel(
            name='AutoCollateral',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='InsuranceCollateral',
        ),
        migrations.DeleteModel(
            name='RealEstateCollateral',
        ),
        migrations.DeleteModel(
            name='Collateral',
        ),
        migrations.DeleteModel(
            name='GoldCollateral',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.DeleteModel(
            name='FinancialInfo',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='LoanDetails',
        ),
    ]
