# Generated by Django 5.2.10 on 2026-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0013_alter_loanagreement_avto_texpasport_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanagreement',
            name='avto_bahosi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Baholangan qiymati'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='avto_yil',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ishlab chiqarilgan yili'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='kredit_miqdori',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Kredit miqdori (raqam bilan)'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='mulk_bahosi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Kelishilgan garov qiymati (raqam)'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='qarz_oluvchi_daromad',
            field=models.BigIntegerField(blank=True, null=True, verbose_name="O'rtacha oylik daromad"),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='qarz_oluvchi_tahminiy_tolov',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Mikroqarz bo‘yicha oylik differensial to‘lovi miqdori (tahminiy)'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='qarz_oluvchi_xarajatlar',
            field=models.BigIntegerField(blank=True, null=True, verbose_name="O'rtacha oylik xarajatlar"),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='sugurta_summasi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Sug'urta summasi (raqam)"),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='tilla_bahosi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Baholangan qiymati'),
        ),
    ]
