# Generated by Django 5.2.12 on 2026-03-23 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0013_remove_autocollateral_collateral_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanwizardapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizard_created', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='loanwizardapplication',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan vaqt'),
        ),
        migrations.AddField(
            model_name='loanwizardapplication',
            name='director_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizard_directed', to=settings.AUTH_USER_MODEL, verbose_name='Direktor'),
        ),
        migrations.AddField(
            model_name='loanwizardapplication',
            name='moderator_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Moderator tasdiqlagan vaqt'),
        ),
        migrations.AddField(
            model_name='loanwizardapplication',
            name='moderator_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizard_moderated', to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
        migrations.AlterField(
            model_name='loanwizardapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('pending_moderator', 'Moderatorga yuborilgan'), ('approved_moderator', 'Moderator tasdiqlagan'), ('approved_director', 'Direktor tasdiqlagan (Yakunlangan)'), ('rejected', 'Rad etilgan')], default='new', max_length=50, verbose_name='Holat'),
        ),
    ]
