# Generated by Django 5.2.10 on 2026-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0014_alter_loanagreement_avto_bahosi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_jshshir',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='JSHSHIR'),
        ),
    ]
