# Generated by Django 5.2.11 on 2026-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0015_loanagreement_qarz_oluvchi_jshshir'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='filial_nomi',
            field=models.CharField(blank=True, choices=[('Buxoro filiali', 'Buxoro filiali'), ('Samarqand filiali', 'Samarqand filiali'), ('Toshkent filiali', 'Toshkent filiali'), ('Andijon filiali', 'Andijon filiali'), ("Farg'ona filiali", "Farg'ona filiali"), ('Namangan filiali', 'Namangan filiali'), ('Qashqadaryo filiali', 'Qashqadaryo filiali'), ('Surxondaryo filiali', 'Surxondaryo filiali'), ('Jizzax filiali', 'Jizzax filiali'), ('Navoiy filiali', 'Navoiy filiali'), ('Xorazm filiali', 'Xorazm filiali')], default='Buxoro filiali', max_length=50, verbose_name='Filial nomi'),
        ),
    ]
