# Generated by Django 5.2.11 on 2026-02-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0016_loanagreement_filial_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='direktor_fish',
            field=models.CharField(blank=True, default="OBIDOV ABDULLA SHOKIR O'G'LI", max_length=255, verbose_name='Direktor F.I.Sh'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='direktor_fish_inisiali',
            field=models.CharField(blank=True, default='A.SH.Obidov', max_length=100, verbose_name='Direktor F.I.Sh (Inisiali)'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='filial_boshligi_inisiali',
            field=models.CharField(blank=True, max_length=100, verbose_name="Filial boshlig'i F.I.Sh (Inisiali)"),
        ),
    ]
