# Generated by Django 5.2.11 on 2026-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0017_loanagreement_direktor_fish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanagreement',
            name='direktor_fish_inisiali',
            field=models.CharField(blank=True, default='A.SH.OBIDOV', max_length=100, verbose_name='Direktor F.I.Sh (Inisiali)'),
        ),
    ]
