# Generated by Django 5.2.11 on 2026-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0018_alter_loanagreement_direktor_fish_inisiali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanagreement',
            name='filial_nomi',
            field=models.CharField(blank=True, choices=[('Buxoro filiali', 'Buxoro filiali'), ('Samarqand filiali', 'Samarqand filiali'), ('Toshkent shahar filiali', 'Toshkent shahar filiali'), ('Andijon filiali', 'Andijon filiali'), ("Farg'ona filiali", "Farg'ona filiali"), ('Namangan filiali', 'Namangan filiali'), ('Qashqadaryo filiali', 'Qashqadaryo filiali'), ('Surxondaryo filiali', 'Surxondaryo filiali'), ('Jizzax filiali', 'Jizzax filiali'), ('Navoiy filiali', 'Navoiy filiali'), ('Xorazm filiali', 'Xorazm filiali'), ("To'rtko'l filiali", "To'rtko'l filiali")], default='Buxoro filiali', max_length=50, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='kontakt_1_qarindoshlik',
            field=models.CharField(blank=True, choices=[('turmush_ortogi', "Turmush o'rtog'i"), ('ota', 'Ota'), ('ona', 'Ona'), ('aka', 'Aka'), ('uka', 'Uka'), ('opa', 'Opa'), ('singil', 'Singil')], max_length=50, verbose_name='1-kontakt Qarindoshligi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='kontakt_2_qarindoshlik',
            field=models.CharField(blank=True, choices=[('turmush_ortogi', "Turmush o'rtog'i"), ('ota', 'Ota'), ('ona', 'Ona'), ('aka', 'Aka'), ('uka', 'Uka'), ('opa', 'Opa'), ('singil', 'Singil')], max_length=50, verbose_name='2-kontakt Qarindoshligi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='kontakt_3_qarindoshlik',
            field=models.CharField(blank=True, choices=[('turmush_ortogi', "Turmush o'rtog'i"), ('ota', 'Ota'), ('ona', 'Ona'), ('aka', 'Aka'), ('uka', 'Uka'), ('opa', 'Opa'), ('singil', 'Singil')], max_length=50, verbose_name='3-kontakt Qarindoshligi'),
        ),
    ]
