# Generated by Django 5.2.11 on 2026-02-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0019_alter_loanagreement_filial_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
    ]
