# Generated by Django 5.2.11 on 2026-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0020_loanagreement_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='new_notary_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notarius manzili'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='new_notary_fish',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notarius F.I.Sh'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='new_owner_fish',
            field=models.CharField(blank=True, max_length=255, verbose_name='Garov egasining F.I.Sh'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='new_owner_initials',
            field=models.CharField(blank=True, max_length=100, verbose_name='Garov egasining inisiali'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='new_registry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reestr sanasi'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='new_registry_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reestr raqami'),
        ),
    ]
