# Generated by Django 5.2.11 on 2026-02-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0021_loanagreement_new_notary_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanagreement',
            name='ishonchnoma_sanasi',
        ),
    ]
