# Generated by Django 5.2.11 on 2026-02-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0022_remove_loanagreement_ishonchnoma_sanasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanagreement',
            old_name='new_owner_initials',
            new_name='garov_egasi_inisiali',
        ),
        migrations.RenameField(
            model_name='loanagreement',
            old_name='new_notary_fish',
            new_name='ishonchnoma_notarius_fish',
        ),
        migrations.RenameField(
            model_name='loanagreement',
            old_name='new_notary_address',
            new_name='ishonchnoma_notarius_manzil',
        ),
        migrations.RenameField(
            model_name='loanagreement',
            old_name='new_registry_number',
            new_name='ishonchnoma_reestr_raqami',
        ),
        migrations.RenameField(
            model_name='loanagreement',
            old_name='new_registry_date',
            new_name='ishonchnoma_reestr_sanasi',
        ),
        migrations.RemoveField(
            model_name='loanagreement',
            name='new_owner_fish',
        ),
    ]
