# Generated by Django 5.2.11 on 2026-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0023_rename_new_owner_initials_loanagreement_garov_egasi_inisiali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_fish_inisiali',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qarz oluvchi F.I.Sh (Inisiali)'),
        ),
    ]
