# Generated by Django 5.2.11 on 2026-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0024_loanagreement_qarz_oluvchi_fish_inisiali'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='qarz_oluvchi_jinsi',
            field=models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
    ]
