# Generated by Django 5.2.11 on 2026-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0025_loanagreement_qarz_oluvchi_jinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='kredit_muddat_oy_soz',
            field=models.CharField(blank=True, max_length=255, verbose_name="Kredit muddati (so'z bilan)"),
        ),
    ]
