# Generated by Django 5.2.11 on 2026-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0026_loanagreement_kredit_muddat_oy_soz'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='tashkilot_nomi',
            field=models.CharField(default='«PULLOL BUSINESS MIKROMOLIYA TASHKILOTI» MChJ', max_length=255, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='filial_boshligi',
            field=models.CharField(blank=True, max_length=255, verbose_name="Filial boshlig'i F.I.Sh"),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='filial_nomi',
            field=models.CharField(choices=[('Buxoro filiali', 'Buxoro filiali'), ('Samarqand filiali', 'Samarqand filiali'), ('Toshkent shahar filiali', 'Toshkent shahar filiali'), ('Andijon filiali', 'Andijon filiali'), ("Farg'ona filiali", "Farg'ona filiali"), ('Namangan filiali', 'Namangan filiali'), ('Qashqadaryo filiali', 'Qashqadaryo filiali'), ('Surxondaryo filiali', 'Surxondaryo filiali'), ('Jizzax filiali', 'Jizzax filiali'), ('Navoiy filiali', 'Navoiy filiali'), ('Xorazm filiali', 'Xorazm filiali'), ("To'rtko'l filiali", "To'rtko'l filiali")], default='Buxoro filiali', max_length=100, verbose_name='Filial nomi'),
        ),
    ]
