# Generated by Django 5.2.11 on 2026-02-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0027_loanagreement_tashkilot_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreement',
            name='mulk_egasi',
            field=models.CharField(blank=True, max_length=255, verbose_name="Ko'chmas mulk egasi"),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='mulk_kadastr_raqami',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kadastr raqami'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='mulk_reestr_raqami',
            field=models.CharField(blank=True, max_length=50, verbose_name='Reestr raqami'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='mulk_qurilish_maydoni',
            field=models.FloatField(blank=True, null=True, verbose_name='Qurilish osti maydoni'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='mulk_umumiy_maydoni',
            field=models.FloatField(blank=True, null=True, verbose_name='Umumiy maydoni'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='mulk_yashash_maydoni',
            field=models.FloatField(blank=True, null=True, verbose_name='Yashash maydoni'),
        ),
    ]
