# Generated by Django 5.2.11 on 2026-02-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0028_loanagreement_mulk_egasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanagreement',
            name='mulk_dalolatnoma_raqami',
        ),
        migrations.RemoveField(
            model_name='loanagreement',
            name='mulk_dalolatnoma_sanasi',
        ),
    ]
